require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - config/**/*
    - bin/**/*
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Naming/VariableNumber:
  EnforcedStyle: snake_case
Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/concerns/*
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/Capybara/FeatureMethods:
  EnabledMethods: [feature, scenario]
