default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: to_dos_development

test:
  <<: *default
  database: to_dos_test

production:
  <<: *default
  database: to_dos_production
