name: actions
on:
  push:
    branches: '*'
jobs:
  quality_control:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
    env:
      RAILS_ENV: test
      JAVASCRIPT_DRIVER: headless_chrome
      INPUT_DATE_FORMAT: '%m/%d/%Y'
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: bundle exec rubocop
      - run: npx eslint .
      - run: bundle exec i18n-tasks health
      - run: cp config/database.github.yml config/database.yml
      - run: bundle exec rails db:setup
      - run: bundle exec rspec
  deploy:
    runs-on: ubuntu-latest
    needs: quality_control
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'whispering-beach-18521'
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: 'https://whispering-beach-18521.herokuapp.com/sessions/new'
